version = 1

exclude_patterns = ["static/**"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["awter-go/db", "awter-go/server", "awter-go/customcrypto"]
  import_root = "github.com/antimatter96/awter-go"

